version: '3'
services:
    compose-service1:
        build: ../cp1-docker-image
        image: my-image
        volumes:
          - "train-volume:/data"
        networks:
          - training-network
    compose-service2:
        build: ../cp1-docker-image
        image: my-image
        volumes:
          - "train-volume:/data"
        environment:
          TARGET: compose-service1
        networks:
          - training-network
volumes:
    train-volume:
      external: true
networks:
    training-network:
        external: true